- name: Get logged-in users on Windows
  hosts: windows
  gather_facts: false # No need for facts in this specific task

  tasks:
    - name: Get process information
      ansible.windows.win_powershell:
        script: |
          query user
      register: explorer_processes
    
    - name: Display captured output
      ansible.builtin.debug:
        msg: "{{ explorer_processes.output }}"
